language: go

services:
    - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

stages:
  - check
  - build
  - test

jobs:
  include:
    - stage: check
      script: ls -la
    - stage: build
      script: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
    - stage: test
      install: go mod download
      script: go test ./... -v
