version: "3.7"

services:
  avocadoro-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avocadoro-backend
    ports:
      - '9090:8080'
    secrets:
      - source: db_password
        target: /app/db_password
      - source: signing_key
        target: /app/signing_key

secrets:
  db_password:
    file:
      keys/db_password
  signing_key:
    file:
      keys/signing_key
