FROM golang:1.14-alpine
WORKDIR /app

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY . .
RUN go get github.com/githubnemo/CompileDaemon
CMD CompileDaemon -command="go run main.go" -exclude-dir=.git -exclude="*.md" -log-prefix=false -graceful-kill=true
