version: "3.7"

services:
  avocadoro-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: avocadoro-backend
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:11-alpine
    container_name: avocadoro-db
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=avocadoro
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: avocadoro-dba
    restart: "unless-stopped"
    ports:
      - 1337:8080

volumes:
  pg_data:
