FROM golang:1.16-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./ ./
RUN go get github.com/githubnemo/CompileDaemon
CMD CompileDaemon -command="./Avocado-Backend" -exclude-dir=.git -exclude="*.md" -log-prefix=false -graceful-kill=true
